"""Print the Swift app's built-in RunPod language list.

The Swift app does not ask a RunPod worker for its languages, because that
starts a billable job. It ships the list that this worker's capabilities()
returns instead. Run this after changing capabilities.py or the WhisperX pin:

    uv run --no-project --with pip python \
        apps/worker-audio-extraction/scripts/export-languages.py \
        > apps/client-macos-swift/Sources/GdayMeetings/Services/RunPodLanguages.swift

It downloads only the pinned WhisperX wheel (no torch) and runs the real
capabilities() against WhisperX's metadata dictionaries, so the output matches
a deployed worker with the default WHISPER_MODEL_SIZE.
"""

import ast
import os
import re
import subprocess
import sys
import tempfile
import types
import zipfile
from pathlib import Path

WORKER = Path(__file__).resolve().parents[1]
OUTPUT = "apps/client-macos-swift/Sources/GdayMeetings/Services/RunPodLanguages.swift"


def pinned_whisperx_version():
    lock = (WORKER / "uv.lock").read_text()
    match = re.search(r'\[\[package\]\]\nname = "whisperx"\nversion = "([^"]+)"', lock)
    if not match:
        sys.exit("whisperx is missing from uv.lock")
    return match.group(1)


def module_constants(source, names):
    """Reads literal module-level assignments without importing the module (which needs torch)."""
    values = {}
    for node in ast.parse(source).body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
            if isinstance(target, ast.Name) and target.id in names:
                values[target.id] = ast.literal_eval(node.value)
    missing = set(names) - set(values)
    if missing:
        sys.exit(f"WhisperX source no longer defines {sorted(missing)} as literals")
    return values


def install_whisperx_stub(version):
    with tempfile.TemporaryDirectory() as directory:
        subprocess.run(
            [sys.executable, "-m", "pip", "download", f"whisperx=={version}", "--no-deps",
             "--only-binary", ":all:", "--quiet", "--dest", directory],
            check=True, stdout=sys.stderr,
        )
        wheel = next(Path(directory).glob("whisperx-*.whl"))
        with zipfile.ZipFile(wheel) as archive:
            utils = archive.read("whisperx/utils.py").decode()
            alignment = archive.read("whisperx/alignment.py").decode()
    package = types.ModuleType("whisperx")
    package.__path__ = []
    for name, source, constants in [
        ("utils", utils, ["LANGUAGES"]),
        ("alignment", alignment, ["DEFAULT_ALIGN_MODELS_HF", "DEFAULT_ALIGN_MODELS_TORCH"]),
    ]:
        module = types.ModuleType(f"whisperx.{name}")
        module.__dict__.update(module_constants(source, constants))
        sys.modules[module.__name__] = module
        setattr(package, name, module)
    sys.modules["whisperx"] = package


def swift_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    version = pinned_whisperx_version()
    install_whisperx_stub(version)
    # Deployed defaults: GPU worker with the default (multilingual) model.
    os.environ.pop("WHISPER_MODEL_SIZE", None)
    os.environ["WHISPER_DEVICE"] = "cuda"
    sys.path.insert(0, str(WORKER / "src"))
    from audio_extraction.capabilities import transcription_languages

    entries = "\n".join(
        f"        ProviderLanguage(code: {swift_string(item['code'])}, name: {swift_string(item['name'])}),"
        for item in transcription_languages()
    )
    print(f"""// Generated by apps/worker-audio-extraction/scripts/export-languages.py. Do not edit.
//
// Source: capabilities.transcription_languages() in
// apps/worker-audio-extraction/src/audio_extraction/capabilities.py, evaluated with
// WhisperX {version} (whisperx/utils.py LANGUAGES and whisperx/alignment.py alignment
// models) and the default multilingual model. A deployed worker built from other
// code can differ; it then rejects the language when the transcription job runs.
//
// Regenerate after changing capabilities.py or the WhisperX pin in uv.lock:
//   uv run --no-project --with pip python apps/worker-audio-extraction/scripts/export-languages.py \\
//       > {OUTPUT}

enum RunPodLanguages {{
    static let whisperXVersion = {swift_string(version)}
    static let all: [ProviderLanguage] = [
{entries}
    ]
}}""")


if __name__ == "__main__":
    main()
