pub mod audio;
pub mod chat;
pub mod filesdb;
pub mod llm;
pub mod markdown;
pub mod people;
pub mod server;
pub mod session;
pub mod settings;
#[cfg(target_os = "macos")]
pub mod system_events;
pub mod tags;
pub mod understanding;
pub mod waveform;
